[package]
name = "example_rust_algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
gaudi_rust_bindings = { version = "0.1.0", path = "../../GaudiRustBindings" }

[lib]
crate-type = ["staticlib"]
