[package]
name = "example_rust_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = { version = "1.0.128", features = ["c++20"]}

[build-dependencies]
cxx-build = { version = "1.0.128", optional = true }

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []
# helpers to invoke Rust functions from C++ are not
# built by default with build.rs, because we may want to use
# the cxxbridge command from (cxxbridge-cmd), e.g. via Corrosion
cxxbind = ["cxx-build"]
